default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

<%= ENV['RAILS_ENV'] %>:
  <<: *default
  database: <%= ENV['DATABASE'] %>